### ISSUE TITLE
VaultStaticSecret kind is not working on Argocd

### ISSUE THREAD

**Issue by makas45** [hashicorp/vault-secrets-operator#627] opened 2024-02-28 19:00 UTC
We have created the vaultstaticsecret and created an argocd application for the same but we got the below error.

```
`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: managed-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: managed-operators/helmcharts/vault-secrets-operator
    repoURL: reponame
    targetRevision: {{ .Values.baseBranch }}
  syncPolicy:
    automated: {}
`
`apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    app.kubernetes.io/managed-by: imagepullsecret-patcher
  name: image-pull-secret
  namespace: zz-workflows
spec:
  destination:
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        ".dockerconfigjson":
          text: |
            {{`{{- $config := .Secrets | mustDeepCopy -}}`}}
            {{- $hostname := get $config "hostname" -}}
            {{- $_ := unset $config "hostname" -}}
            {{- $_ := set $config "auth" (list (get .Secrets "username") ":" (get .Secrets "password") | join "" | b64enc) -}}
            {{- dict "auths" (dict $hostname $config) | mustToJson -}}
    labels:
      vss: "true"
    create: true
    name: image-pull-secret
    overwrite: false
    type: kubernetes.io/dockerconfigjson
  hmacSecretData: true
  mount: secret
  path: image-pull-secret
  type: kv-v2
  namespace: openshift
  vaultAuthRef: vault-auth`
```
Error message
`
ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template vault-secrets-operator --namespace managed-operators --kube-version 1.28 <api versions removed> --include-crds` failed exit status 1: Error: parse error at (vault-secrets-operator/templates/vault-conn-auth.yaml:73): undefined variable "$config" Use --debug flag to render out invalid YAML Error: `

**Comment by benashz** [comment] 2024-03-06 21:22
@makas45 - when we run the `helm template` command above in the `chart` directory we don't have any errors.

```
 $ helm template . --name-template vault-secrets-operator --namespace managed-operators --kube-version 1.28 --include-crds > /dev/null ; echo $?
0
```

Also, our official VSO chart does not seem to contain the file `./templates/vault-conn-auth.yaml`, is that a custom file? Are you trying to install/upgrade a custom chart? What does line 73 in `vault-secrets-operator/templates/vault-conn-auth.yaml` look like?

**Comment by benashz** [comment] 2024-03-07 17:26
Hi @makas45 , I believe Helm template rendering issue is a duplicate of https://github.com/hashicorp/vault-secrets-operator/issues/619#issuecomment-1966625624 - I have posted a solution here: https://github.com/hashicorp/vault-secrets-operator/issues/619#issuecomment-1984053146

**Closed** 2024-03-11 15:38 UTC
Labels: documentation, secret-transformation
