### ISSUE TITLE
Support more dynamic secret paths

### ISSUE THREAD

**Issue by adrianmoisey** [hashicorp/vault-secrets-operator#107] opened 2023-04-03 15:04 UTC
**Describe the bug**
The Vault Secrets Operator fails to work on dynamic secret paths other than AWS.
The operator has "/creds/" hardcoded in the path: https://github.com/hashicorp/vault-secrets-operator/blame/f617b4aa2f2572414d7039774ee1170f8f6e3a08/controllers/vaultdynamicsecret_controller.go#L209

Some backends, such as GCP, don't use "/creds/"

**To Reproduce**
1. Configure Vault with a GCP backend
2. Install and configure the Vault Secrets Operator
3. Configure a "VaultDynamicSecret" CR pointing at a secret in Vault
5. See error in the vault-operator logs:

```
2023-04-03T14:49:40Z	ERROR	Reconciler error	{"controller": "vaultdynamicsecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultDynamicSecret", "VaultDynamicSecret": {"name":"vaultdynamicsecret-sample","namespace":"default"}, "namespace": "default", "name": "vaultdynamicsecret-sample", "reconcileID": "1321a336-0f52-4f27-9e62-2fa69fc28e41", "error": "Error making API request.\n\nURL: GET https://vault.default.svc.cluster.local:8200/v1/gcp/creds/roleset/bucket/token\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"}
``` 

The main part of that output is the following:
> Error making API request.\n\nURL: GET https://vault.default.svc.cluster.local:8200/v1/gcp/creds/roleset/bucket/token\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"

This is due to the GCP backend not having a secret on the path "gcp/creds/roleset/bucket/token".
The problem is that "creds" is injected into the path.

Application deployment:

Deployed using the Helm chart
```yaml
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultConnection
metadata:
  name: vaultconnection-sample
  namespace: default
spec:
  address: https://vault.default.svc.cluster.local:8200
  caCertSecretRef: vault-tls
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  name: vaultauth-sample
  namespace: default
spec:
  vaultConnectionRef: vaultconnection-sample
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: default
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vaultdynamicsecret-sample
spec:
  vaultAuthRef: vaultauth-sample
  mount: gcp
  role: roleset/bucket/token
  destination:
    name: vault-secret-output
```

**Expected behavior**
The secret to be fetched on the correct path 

**Environment**
* vault-secrets-operator version:
0.1.0-beta

**Additional context**
None

**Comment by adrianmoisey** [comment] 2023-04-03 15:05
Another thing to note: https://developer.hashicorp.com/vault/docs/secrets/aws#sts-federation-tokens

AWS STS credentials are fetched on the path `aws/sts`, so they will also break with this scheme

**Comment by sebglon** [comment] 2023-04-11 12:25
When i generate an AWS dynamic with role that is configured as `assumed_role`, the `vaultDynamicSecret` use the path `aws/creds/my-role` and not the `aws/sts/my-role`.
But it seems working. i have the keys

**Comment by ameyp** [comment] 2023-04-15 18:31
What about support for static database roles, where the username stays the same but the password changes?

**Comment by adrianmoisey** [comment] 2023-04-15 19:07
> What about support for static database roles, where the username stays the same but the password changes?

If those are formatted as `<engine path>/creds/<role>`, then they should be supported at the moment.
If they don't, then you'll need to wait until the bug fix has been made.

**Comment by ameyp** [comment] 2023-04-15 19:10
It's a different path, so I'll wait for your PR to get merged

**Comment by jbouse** [comment] 2023-04-18 00:40
> > What about support for static database roles, where the username stays the same but the password changes?
> 
> If those are formatted as `<engine path>/creds/<role>`, then they should be supported at the moment. If they don't, then you'll need to wait until the bug fix has been made.

Actually, static database roles use `<database secret mount path>/static-creds/<role>` which I just found out while trying to set up a vaultDynamicSecret to attempt to get the static role credentials and found it failing for the reasons mentioned here.

**Comment by adrianmoisey** [comment] 2023-05-02 19:36
@benashz is there any update on this issue?

**Comment by benashz** [comment] 2023-05-02 19:44
Hi @adrianmoisey! We are currently working on it. It should be going out in the upcoming [v0.1.0-beta.1](https://github.com/hashicorp/vault-secrets-operator/milestone/1) release.

**Comment by benashz** [comment] 2023-05-05 19:35
Duplicate of #108

**Closed** 2023-05-16 19:27 UTC
Labels: bug, dynamic
