### ISSUE TITLE
Update vaultAuthRef on existing Dynamic secret is not used

### ISSUE THREAD

**Issue by sebglon** [hashicorp/vault-secrets-operator#126] opened 2023-04-11 19:01 UTC
**Describe the bug**
After updating the `vaultAuthRef` the reconcile is not done with the new auth

**To Reproduce**
1. create a `vaultdynamicsecret` with a bad `vaultAuthRef`.
2. we have an error on the describe event:
`Warning  VaultClientConfigError  10m (x10 over 14m)  VaultDynamicSecret  Failed to get Vault client: VaultAuth.secrets.hashicorp.com "bad-vault-auth" not found, lease_id=`
4. Update the `vaultAuthRef`
5. the describe does not have new event (with the new or old `vaultAuthRef`)
6. the K8s secret is not generated

**Expected behavior**
The reconcile is success and the secret is created

**Environment**
* Kubernetes version: 1.22.2
* vault-secrets-operator version: 0.11.0

**Comment by benashz** [comment] 2023-04-12 13:11
Hi @sebglon, we are not able to reproduce this issue. Would you be able to provide us with a bit more info?

- The `Spec` `Status` of the VaultDynamicSecret (before and after)
- The `Status` of the VaultDynamicSecret during the failure, and after providing a valid `vaultAuthRef`

Thanks,

Ben

**Comment by benashz** [comment] 2023-05-02 20:23
Going to close this out for now. Please reopen if the issue pops up again. Thanks!

**Closed by benashz** 2023-05-02 20:23 UTC
Labels: bug, dynamic
