### ISSUE TITLE
Vault Secrets Operator memory usage way too high

### ISSUE THREAD

**Issue by cascadia-sati** [hashicorp/vault-secrets-operator#969] opened 2024-11-12 15:15 UTC
**Describe the bug**
We have Vault 1.16.1 and Vault Secrets Manager 0.7.1 running in our dev, sandbox, and prod EKS 1.26 clusters. The vault-secrets-manager pod is using a lot more memory than the default 128 MB limit defined in the chart's value file, despite only syncing around 60 secrets. At startup this sometimes even spikes to well above 256 MB, so we had to set the limit to 512 MB.

Recently the VSO pod in the dev cluster started getting OOMKilled again, so we had to increase the limit once more. For some reason the VSO pod in dev is using more than double the memory of the ones running in sandbox and prod, even though the number of secrets is relatively the same across all envs.

Dev:
```
$ k top pod vault-secrets-operator-controller-manager-5cf49f6444-f6j7w
NAME                                                         CPU(cores)   MEMORY(bytes)
vault-secrets-operator-controller-manager-5cf49f6444-f6j7w   6m           426Mi

$ k get vaultstaticsecret -A | wc -l
      61
```

Sandbox:
```
$ k top pod vault-secrets-operator-controller-manager-66d4c79c6d-wfb8j
NAME                                                         CPU(cores)   MEMORY(bytes)
vault-secrets-operator-controller-manager-66d4c79c6d-wfb8j   6m           189Mi

$ k get vaultstaticsecret -A | wc -l
      63
```

Prod:
```
$ k top pod vault-secrets-operator-controller-manager-57cccf65c5-mm4ql
NAME                                                         CPU(cores)   MEMORY(bytes)
vault-secrets-operator-controller-manager-57cccf65c5-mm4ql   8m           157Mi

$ k get vaultstaticsecret -A | wc -l
      60
```

Here is dev at its peak:
```
$ kubectl top pod vault-secrets-operator-controller-manager-5cf49f6444-97skb
NAME                                                         CPU(cores)   MEMORY(bytes)
vault-secrets-operator-controller-manager-5cf49f6444-97skb   3m           839Mi
```

I tried upgrading VSO in dev to 0.9.0, but nothing changed.

Our setup is very basic out of the box.

Each secret has no more than a couple dozen values, most of them much less.

My questions are:

1) Why does the VSO pod use more memory than the default limit in such a basic scenario?

2) Why does the VSO pod need so much memory in general?

3) Why does the dev VSO pod need more than twice the memory of the pod in the other envs despite syncing the same number of secrets? Or how can we find this out?

**Comment by cascadia-sati** [comment] 2024-11-25 17:00
Hi @tvoran, thanks so much for taking the time to reply.

Yes, we're only using VaultStaticSecrets with a refresh of 30s.

We're using exclusively the kubernetes auth method with a token expiration of 600 seconds.

Our dev env has 61 secrets and our prod has 60, so pretty much the same and all around a small number.

No errors in the logs for either env.

Let me know what you recommend we should check. Thanks again.

**Comment by benashz** [comment] 2024-12-10 19:26
Duplicate of #973

**Closed by benashz** 2024-12-10 19:26 UTC
Labels: bug, memory usage

**Comment by benashz** [comment] 2024-12-13 16:46
Hi @cascadia-sati ,  the most recent release [v0.9.1](https://github.com/hashicorp/vault-secrets-operator/releases/tag/v0.9.1) of VSO should address the memory issue that you have been experiencing. Please let us know if you are still seeing the issue after upgrading. Upgrade instructions can be found [here](https://developer.hashicorp.com/vault/docs/platform/k8s/vso/installation).

Thanks!

**Comment by cascadia-sati** [comment] 2024-12-16 11:33
Thanks @benashz! We upgraded in all of our envs and saw a drastic reduction in memory usage:

Dev: 451 MB -> 97 MB

Sandbox: 204 MB -> 64 MB

Prod: 182 MB -> 61 MB
